# Generated by Django 5.0 on 2024-05-05 19:14

import django.db.models.deletion
import functools
import nanoid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(nanoid.generate, *(), **{"size": 12}),
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="documents/")),
            ],
            options={
                "db_table": "document",
            },
        ),
        migrations.CreateModel(
            name="SMS",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(nanoid.generate, *(), **{"size": 12}),
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resend_at", models.DateTimeField(null=True)),
                ("can_resend_at", models.DateTimeField(null=True)),
                ("can_resend", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "sms",
            },
        ),
        migrations.CreateModel(
            name="DocumentSigningRequest",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(nanoid.generate, *(), **{"size": 12}),
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("code", models.CharField(max_length=4)),
                ("attempts", models.IntegerField(default=0)),
                ("signed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(null=True)),
                ("signed_at", models.DateTimeField(null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.document"
                    ),
                ),
                (
                    "sms",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.sms"
                    ),
                ),
            ],
            options={
                "db_table": "document_signing_request_new",
            },
        ),
    ]
