# Generated by Django 5.0 on 2024-05-06 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="documentsigningrequest",
            table="document_signing_request",
        ),
    ]
