# Generated by Django 5.0.4 on 2024-04-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentSigningRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("phone_number", models.CharField(max_length=20)),
                ("code", models.CharField(max_length=8)),
                ("document", models.FileField(upload_to="signined_documents/")),
                (
                    "sms_status_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
