# Generated by Django 5.0.4 on 2024-04-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="documentsigningrequest",
            table="document_signing_request",
        ),
    ]
