# Generated by Django 5.0.4 on 2024-04-15 14:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_alter_documentsigningrequest_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentsigningrequest",
            name="document",
        ),
        migrations.RemoveField(
            model_name="documentsigningrequest",
            name="sms_status_code",
        ),
        migrations.RemoveField(
            model_name="documentsigningrequest",
            name="id",
        ),
        migrations.AddField(
            model_name="documentsigningrequest",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
