# Generated by Django 5.0.4 on 2024-04-15 14:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0004_remove_documentsigningrequest_document_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMS",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status_code", models.IntegerField()),
            ],
            options={
                "db_table": "sms",
            },
        ),
        migrations.RenameField(
            model_name="documentsigningrequest",
            old_name="code",
            new_name="confirmation_code",
        ),
        migrations.AddField(
            model_name="documentsigningrequest",
            name="document",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentsigningrequest",
            name="sms",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_panel.sms",
            ),
        ),
    ]
