# Generated by Django 5.0.4 on 2024-04-15 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0005_sms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sms",
            name="phone_number",
            field=models.CharField(null=False, max_length=20),
            preserve_default=False,
        ),
    ]
