# Generated by Django 5.0.4 on 2024-04-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0006_sms_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsigningrequest",
            name="signed",
            field=models.BooleanField(default=False),
        ),
    ]
