# Generated by Django 5.0.4 on 2024-04-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0008_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentsigningrequest",
            name="document",
        ),
        migrations.AddField(
            model_name="documentsigningrequest",
            name="documents",
            field=models.ManyToManyField(
                related_name="request_document", to="admin_panel.document"
            ),
        ),
    ]
