# Generated by Django 5.0.4 on 2024-04-22 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0010_documentsigningrequest_expires_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentsigningrequest",
            name="documents",
        ),
        migrations.AddField(
            model_name="documentsigningrequest",
            name="document",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_panel.document",
            ),
            preserve_default=False,
        ),
    ]
