# Generated by Django 5.0.4 on 2024-04-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0011_remove_documentsigningrequest_documents_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsigningrequest",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="documentsigningrequest",
            name="attempts",
            field=models.IntegerField(default=0),
        ),
    ]
