# Generated by Django 5.0.4 on 2024-04-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0012_documentsigningrequest_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentsigningrequest",
            name="active",
        ),
        migrations.AddField(
            model_name="documentsigningrequest",
            name="can_resend_sms",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="documentsigningrequest",
            name="resened_sms_from",
            field=models.DateTimeField(null=True),
        ),
    ]
