# Generated by Django 5.0.4 on 2024-04-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0013_remove_documentsigningrequest_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documentsigningrequest",
            old_name="resened_sms_from",
            new_name="resend_sms_from",
        ),
    ]
