# Generated by Django 5.0.4 on 2024-04-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_panel",
            "0014_rename_resened_sms_from_documentsigningrequest_resend_sms_from",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="template",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(null=True, upload_to="documents/"),
        ),
    ]
