# Generated by Django 5.0.4 on 2024-04-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0015_document_template_alter_document_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="file",
        ),
        migrations.AlterField(
            model_name="document",
            name="template",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
