# Generated by Django 5.0.4 on 2024-04-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0016_remove_document_file_alter_document_template"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentsigningrequest",
            name="document",
        ),
        migrations.AddField(
            model_name="documentsigningrequest",
            name="document_file",
            field=models.FileField(default="", upload_to="request_documents/"),
            preserve_default=False,
        ),
    ]
