# Generated by Django 5.0.4 on 2024-04-28 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0017_remove_documentsigningrequest_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsigningrequest",
            name="document_content",
            field=models.TextField(
                default=datetime.datetime(
                    2024, 4, 28, 17, 4, 9, 664497, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentsigningrequest",
            name="signed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="documentsigningrequest",
            name="document_file",
            field=models.FileField(upload_to="documents/"),
        ),
    ]
