# Generated by Django 5.0.4 on 2024-04-29 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0018_documentsigningrequest_document_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsigningrequest",
            name="document",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_panel.document",
            ),
            preserve_default=False,
        ),
    ]
