# Generated by Django 5.0 on 2024-05-01 08:00

import functools
import nanoid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0019_documentsigningrequest_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsigningrequest",
            name="id",
            field=models.CharField(
                default=functools.partial(
                    nanoid.generate,
                    *(),
                    **{
                        "size": 12,
                    }
                ),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
