# Generated by Django 5.0 on 2024-05-05 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0020_alter_documentsigningrequest_id"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="document",
            table="document_old",
        ),
        migrations.AlterModelTable(
            name="documentsigningrequest",
            table="document_signing_request_old",
        ),
        migrations.AlterModelTable(
            name="sms",
            table="sms_old",
        ),
    ]
