# Generated by Django 5.0 on 2024-05-06 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0021_alter_document_table_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentsigningrequest",
            name="document",
        ),
        migrations.RemoveField(
            model_name="documentsigningrequest",
            name="sms",
        ),
        migrations.DeleteModel(
            name="Document",
        ),
        migrations.DeleteModel(
            name="DocumentSigningRequest",
        ),
        migrations.DeleteModel(
            name="SMS",
        ),
    ]
